# Generated by Django 6.0 on 2025-12-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='virtual_tour_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на 3D-тур (виртуальная экскурсия)'),
        ),
    ]
